
require("dotenv").config();

const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
    }
});

async function verifyGmailConnection() {
    await transporter.verify();

    console.log("Gmail connection verified successfully.");
}

function formatJobDetails(job) {
    return `
Company: ${job.company || "Not specified"}
Role: ${job.title || "Not specified"}
Match Type: ${job.match?.status || "Not specified"}
Match Score: ${job.match?.score ?? "Not specified"}
Location: ${(job.locations || []).join(", ") || job.location || "Not specified"}
Required QA Experience: ${job.minimumExperience || "Not specified"}
Required Automation Experience: ${job.automationExperience || "Not specified"}
Technologies: ${(job.technologies || []).join(", ") || "Not specified"}
Application URL: ${job.url || "Not available"}
`.trim();
}

async function sendJobAlert(job) {
    const mailOptions = {
        from: process.env.GMAIL_USER,
        to: process.env.GMAIL_USER,
        subject: `QA Job Alert: ${job.title}`,
        text: `
New QA job match found!

${formatJobDetails(job)}

This alert was generated by QA Job Hunter.
        `.trim()
    };

    const info = await transporter.sendMail(mailOptions);

    console.log(`Email sent successfully: ${info.messageId}`);

    return info;
}

async function sendJobDigest(jobs, emailSender) {
    if (!Array.isArray(jobs) || jobs.length === 0) {
        return {
            sent: false,
            reason: "NO_JOBS",
            count: 0
        };
    }

    const strongMatches = jobs.filter(
        job => job.match?.status === "STRONG_MATCH"
    );

    const reviewMatches = jobs.filter(
        job => job.match?.status === "REVIEW_MATCH"
    );

    const sections = [];

    if (strongMatches.length > 0) {
        sections.push(
            "========== STRONG MATCHES ==========\n\n" +
            strongMatches.map(formatJobDetails).join("\n\n----------------------------------------\n\n")
        );
    }

    if (reviewMatches.length > 0) {
        sections.push(
            "========== REVIEW MATCHES ==========\n\n" +
            reviewMatches.map(formatJobDetails).join("\n\n----------------------------------------\n\n")
        );
    }

    const mailOptions = {
        from: process.env.GMAIL_USER,
        to: process.env.GMAIL_USER,
        subject: `QA Job Hunter Daily Digest: ${jobs.length} matching job(s)`,
        text: `
Your QA Job Hunter digest is ready.

Strong matches: ${strongMatches.length}
Review matches: ${reviewMatches.length}
Total jobs: ${jobs.length}

${sections.join("\n\n========================================\n\n")}

Review each job description and confirm its requirements before applying.

This digest was generated by QA Job Hunter.
        `.trim()
    };

    // Allow tests to supply a fake sender so they never contact Gmail.
    const sender = emailSender || (
        options => transporter.sendMail(options)
    );

    const info = await sender(mailOptions);

    console.log(`Digest email sent successfully: ${info.messageId || "sender confirmed delivery"}`);

    return {
        sent: true,
        count: jobs.length,
        strongMatches: strongMatches.length,
        reviewMatches: reviewMatches.length,
        messageId: info.messageId || null
    };
}

module.exports = {
    verifyGmailConnection,
    sendJobAlert,
    sendJobDigest,
    formatJobDetails
};
