require("dotenv").config();

const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
    }
});

async function verifyGmailConnection() {
    await transporter.verify();

    console.log("Gmail connection verified successfully.");
}

async function sendJobAlert(job) {
    const mailOptions = {
        from: process.env.GMAIL_USER,
        to: process.env.GMAIL_USER,
        subject: `QA Job Alert: ${job.title}`,
        text: `
New QA job match found!

Company: ${job.company}
Role: ${job.title}
Match Type: ${job.match.status}
Match Score: ${job.match.score}

Location:
${(job.locations || []).join(", ") || "Not specified"}

Required QA Experience:
${job.minimumExperience || "Not specified"}

Required Automation Experience:
${job.automationExperience || "Not specified"}

Technologies:
${(job.technologies || []).join(", ") || "Not specified"}

Application URL:
${job.url}

This alert was generated by QA Job Hunter.
        `.trim()
    };

    const info = await transporter.sendMail(mailOptions);

    console.log(`Email sent successfully: ${info.messageId}`);

    return info;
}

module.exports = {
    verifyGmailConnection,
    sendJobAlert
};